registryCredentialsSecret: registry-credentials

elasticsearch:
  fullnameOverride: ai-sprint-monit-elasticsearch
  ingress:
    enabled: true
    hosts:
      - host: elasticsearch.ai-sprint.local
        paths:
          - path: /
  roles:
    master: "true"
    ingest: "true"
    data: "true"
  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ai-sprint-monit-elastic-credentials
          key: password
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: ai-sprint-monit-elastic-credentials
          key: username

kibana:
  fullnameOverride: ai-sprint-monit-kibana
  elasticsearchHosts: "http://ai-sprint-monit-elasticsearch:9200"
  ingress:
    enabled: true
    hosts:
      - host: kibana.ai-sprint.local
        paths:
          - path: /
  extraEnvs:
    - name: 'ELASTICSEARCH_USERNAME'
      valueFrom:
        secretKeyRef:
          name: ai-sprint-monit-elastic-credentials
          key: username
    - name: 'ELASTICSEARCH_PASSWORD'
      valueFrom:
        secretKeyRef:
          name: ai-sprint-monit-elastic-credentials
          key: password
