apiVersion: v1
data:
  password: {{ randAlphaNum 16 | b64enc }}
  username: YWRtaW4K 
kind: Secret
metadata:
  name: ai-sprint-monit-elastic-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
